# Generated by Django 5.2.2 on 2025-06-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.CharField(blank=True, null=True),
        ),
    ]
