# Generated by Django 5.2.2 on 2025-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_detail_product_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
